spring:
  profiles:
    active: test
  cloud:
    config:
      request-connect-timeout: 5000
      request-read-timeout: 30000
      fail-fast: true
  config:
    import: "optional:configserver:http://configserver:8888"
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: Pali$8619216837
  datasource:  
    url: jdbc:postgresql://postgresql:5432/company_service_db
    username: job_user
    password: Pali$8619216837
  jpa:
      properties:
        hibernate:
          format_sql: true
          show_sql: true
          jdbc:
            time_zone: Asia/Kolkata
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      shutdown:
        access: unrestricted
      health:
        show-details: always
    info:
      env:
        enabled: true

server:
    port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: "http://eureka-service:8761/eureka"
    fetch-registry: true
    register-with-eureka: true

jobs:
  service:
    url: http://jobs-service:8082

companies:
  service:
    url: http://companies-service:8081

reviews:
  service:
    url: http://reviews-service:8083
